### ISSUE TITLE
fails in julia v0.4

### ISSUE THREAD

**Issue by montyvesselinov** [JuliaStats/NMF.jl#10]
W, H = NMF.randinit(X, 3)
ERROR: TypeError: typeassert: expected Type{T}, got Tuple{DataType,DataType}
 in randinit at /Users/monty/.julia/v0.4/NMF/src/initialization.jl:13

**Comment by lendle** [comment]
Looks like this is fixed on master. Can someone tag a new version in METADATA?

**Comment by yvesx** [comment]
+1
`> Pkg.checkout("NMF")` works for v0.4

**Comment by silenj** [comment]
But at least alg=:alspgrad gives errors still like:
ERROR: TypeError: typeassert: expected Type{T}, got Tuple{DataType,DataType}
 in posnegnorm at /home/silenj/.julia/v0.4/NMF/src/initialization.jl:111
 in _nndsvd! at /home/silenj/.julia/v0.4/NMF/src/initialization.jl:43
 in nndsvd at /home/silenj/.julia/v0.4/NMF/src/initialization.jl:90
 in nnmf at /home/silenj/.julia/v0.4/NMF/src/interf.jl:26

I made some small changes (make the tuples types separated) in the package to have a working system. I can provide the patches when I learn enough of git  to do it   ;)

**Comment by slundberg** [comment]
Any update on this?

**Comment by ararslan** [comment]
The newly tagged NMF v0.2.5 is installable and works in Julia 0.3, 0.4, and 0.5.
